apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lw-agents
  labels:
    app.kubernetes.io/name: lw-agents
spec:
  to:
    kind: Service
    name: lw-agents
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
