apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: tssc-agents

images:
  - name: quay.io/placeholder/lw-agents
    newName: ghcr.io/rrbanda/lw-agents
    newTag: latest
